set cscopeprg=gtags-cscope
if filereadable("GTAGS")
    execute "cs add GTAGS"
endif
if filereadable("Session.vim")
    execute "source Session.vim"
    autocmd VimLeave * :mksession!
endif
if !has("gui_running")
    set mouse-=a
    set nocursorline
else
    if has('win32')
        set guifont=Consolas:h15:cANSI
    elseif has('unix')
        set guifont=Monospace\ 15
    endif
    set mouse+=a
    set cursorline
    nmap <C-RightMouse> <C-O>
    set guioptions-=m
endif
set hlsearch
set ignorecase
set smartcase
set nobackup
set nowrap
nmap <C-A> :set wrap!<CR>
syntax on
set laststatus=2
set statusline=%F%m%r\ (Line=%l\|%p%%)
set smarttab
set tabstop=4
set shiftwidth=4
set expandtab
set autoindent
set showcmd
set nocompatible
set backspace=indent,eol,start
filetype plugin indent on
let Tlist_Show_One_File=1
let Tlist_Exit_OnlyWindow=1
nmap <C-L> :TlistToggle<CR>
nmap <C-G> :!global -u<CR>
nmap ff :cs find f <C-R><C-F><CR>
nmap fg :cs find g <C-R><C-W><CR>
nmap fG :cs find g 
nmap fs :cs find s <C-R><C-W><CR>
language C
set cscopequickfix=s-,c-,d-,i-,t-,e-,g-
set cst
nmap co :copen<CR>
nmap cc :cclose<CR>
let g:ctrlp_use_caching = 1
let g:ctrlp_clear_cache_on_exit = 0
let g:ctrlp_working_path_mode = 0
let g:ctrlp_lazy_update = 1
let g:ctrlp_extensions = ['funky']
let mapleader = ";"
nmap <C-B> :CtrlPMRUFiles<CR>
nmap <C-E> :e %:h<CR>
set showcmd
set fileencodings=utf-8,gb2312,cp936
set termencoding=utf-8
set encoding=utf-8
fun! AddCs()
    if filereadable(expand("%:h") . "/GTAGS")
        cd %:h
        cs add GTAGS
    endif
endfun
autocmd BufRead *.cpp,*.c,*.hpp,*.h,Makefile*,makefile* call AddCs()
nmap <C-D> :!start /B echo ^<head^>^<meta charset="utf-8"^>^</head^> >\%TMP\%/%:t.html&&markdown % >>\%TMP\%/%:t.html&&\%TMP\%/%:t.html<CR><CR>
imap <C-D> <C-O><C-D>
vmap <C-F> "+y<C-C>:vim "<C-R>"" %<CR>:copen<CR>
vmap <C-C> "+y
imap <C-V> <C-O>"+P
cmap <C-V> <C-R>+
imap <C-X> <C-O>"+d
imap <C-S> <C-O>:w<CR>
imap <C-Z> <C-O><C-Z>
autocmd BufReadPost,FileReadPost * '"
set cm=blowfish2
fun! CurDirShell()
    cd %:h
    if !has("gui_running")
        shell
    else
        if has('win32')
            silent shell
        else
            echo "use <C-Z>"
        endif
    endif
    cd -
endfun
nmap ss :call CurDirShell()<CR>
