(add-to-list 'load-path (expand-file-name "~/.emacs.d/lisp"))
(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(setq create-lockfiles nil)
(global-auto-revert-mode t)
(require 'recentf)
(recentf-mode t)
(global-set-key (kbd "<f2>") 'recentf-open-files)
(global-set-key (kbd "<f3>") 'highlight-regexp)
(global-set-key (kbd "C-c <f3>") 'list-matching-lines)
(global-set-key (kbd "TAB") '(lambda()(interactive)(insert "\t")))
(global-set-key (kbd "C-x C-c") 'save-buffers-kill-emacs)
(fset 'save-buffers-kill-emacs '(lambda()(interactive)(save-some-buffers nil t)(kill-emacs)))
(setq-default indent-tabs-mode nil)
(setq c-basic-offset 4)
(setq-default tab-width 4)
(c-set-offset 'innamespace 0)
(show-paren-mode t)
(set-default 'truncate-lines t)
(setq-default cursor-type 'bar)
(which-function-mode)
(column-number-mode)
(fset 'yes-or-no-p 'y-or-n-p)
(add-hook 'prog-mode-hook '(lambda()(require 'gtags)(gtags-mode)(require 'taglist)(local-set-key (kbd "<f4>") 'taglist-list-tags)))
(setq gtags-suggested-key-mapping t)
(setq gtags-auto-update t)
(if (eq system-type 'windows-nt) (concat (setenv "PATH" "E:/bin/msys2/usr/bin;")(getenv "PATH")))
(if (display-graphic-p)(progn (if (eq system-type 'windows-nt) (progn (setq enfont "Courier New")(setq cnfont "Microsoft Yahei")) (progn (setq enfont "DejaVu Sans Mono")(setq cnfont "WenQuanYi Bitmap Song"))) (set-face-attribute 'default nil :font enfont :height 128) (set-fontset-font (frame-parameter nil 'font) 'han (font-spec :family cnfont :size 19))))
(setq large-file-warning-threshold nil)
(setq ring-bell-function 'ignore)
(prefer-coding-system 'gb2312)
(setq default-buffer-file-coding-system 'utf-8-unix)
(setq mouse-wheel-progressive-speed nil)
(set-background-color "gray25")
(set-foreground-color "white")
