(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(require 'recentf)
(recentf-mode t)
(global-set-key (kbd "<f5>") 'speedbar)
(global-set-key (kbd "<f12>") 'gtags-mode)
(setq-default indent-tabs-mode nil)
(setq c-basic-offset 4)
(show-paren-mode t)
(setq-default mode-line-format "%*%b%* (%f) (%l, %c) %p %m")
(fset 'yes-or-no-p 'y-or-n-p)
(setq gtags-suggested-key-mapping t)
(load "gtags")
(add-hook 'find-file-hooks (lambda()(toggle-read-only t)))
(setq column-number-mode t)
(server-start)
