(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(require 'recentf)
(recentf-mode t)
(global-set-key (kbd "C-c m") 'set-mark-command)
(global-set-key (kbd "C-c l") 'list-matching-lines)
(global-set-key (kbd "C-c o") 'read-only-mode)
(global-set-key (kbd "<f2>") 'recentf-open-files)
(global-set-key (kbd "<f5>") 'speedbar)
(setq-default indent-tabs-mode nil)
(setq c-basic-offset 4)
(show-paren-mode t)
(setq-default cursor-type 'bar)
(setq-default mode-line-format "%*%b%* (%f) (%l, %c) %p %m")
(fset 'yes-or-no-p 'y-or-n-p)
(add-hook 'c-mode-common-hook 'gtags-mode)
(setq gtags-suggested-key-mapping t)
(load "gtags")
(add-hook 'find-file-hooks (lambda()(toggle-read-only t)))
(setq column-number-mode t)
(set-default-font "-outline-微软雅黑-normal-normal-normal-sans-13-*-*-*-p-*-iso8859-1")
(prefer-coding-system 'utf-8)
(load "unicad")
(server-start)
