(global-set-key (kbd "<C-wheel-up>") 'text-scale-increase)
(global-set-key (kbd "<C-wheel-down>") 'text-scale-decrease)
(setq inhibit-startup-message t)
(setq make-backup-files nil)
(setq auto-save-default nil)
(require 'recentf)
(recentf-mode t)
(global-set-key (kbd "<f5>") 'speedbar)
(global-set-key (kbd "<f12>") 'gtags-mode)
(setq indent-tabs-mode nil)
(fset 'yes-or-no-p 'y-or-n-p)
(setq gtags-suggested-key-mapping t)
(load "gtags")

